In [1]:
import os
import pandas as pd
import numpy as np
from glob import glob

# Data Preprocessing

In [2]:
path_list = glob(os.path.join(os.getcwd(), 'dataset', '*'))
path_list

['/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/Y_train',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/test.csv',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/X_train',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/train.csv',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/X_test',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/sample_submission.csv']

In [3]:
path_Y_train = path_list[0]
df_Y_train = pd.read_csv(path_Y_train)
df_Y_train

       label
0          0
1          0
2          0
3          0
4          0
5          0
6          0
7          1
8          1
9          1
10         1
11         1
12         0
13         0
14         1
15         0
16         0
17         0
18         0
19         1
20         1
21         0
22         0
23         0
24         0
25         1
26         0
27         1
28         0
29         0
...      ...
32531      0
32532      1
32533      1
32534      0
32535      0
32536      1
32537      0
32538      1
32539      1
32540      0
32541      0
32542      0
32543      0
32544      0
32545      1
32546      0
32547      0
32548      0
32549      0
32550      0
32551      0
32552      0
32553      0
32554      1
32555      0
32556      0
32557      1
32558      0
32559      0
32560      1

[32561 rows x 1 columns]

In [4]:
path_X_train = path_list[2]
df_X_train = pd.read_csv(path_X_train)
df_X_train

,age,fnlwgt,sex,capital_gain,capital_loss,hours_per_week,Federal-gov,Local-gov,Never-worked,Private,...,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia,?_native_country
0,39,77516,1,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,50,83311,1,0,0,13,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,38,215646,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,53,234721,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,28,338409,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,37,284582,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
6,49,160187,0,0,0,16,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,52,209642,1,0,0,45,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8,31,45781,0,14084,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
9,42,159449,1,5178,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
10,37,280464,1,0,0,80,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
11,30,141297,1,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,23,122272,0,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
13,32,205019,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
14,40,121772,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
15,34,245487,1,0,0,45,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,25,176756,1,0,0,35,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
17,32,186824,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
18,38,28887,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
19,43,292175,0,0,0,45,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,40,193524,1,0,0,60,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
21,54,302146,0,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
22,35,76845,1,0,0,40,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
23,43,117037,1,0,2042,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
24,59,109015,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
25,56,216851,1,0,0,40,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
26,19,168294,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
27,54,180211,1,0,0,60,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
28,39,367260,1,0,0,80,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
29,49,193366,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,33811,0,0,0,99,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32532,34,204461,1,0,0,60,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32533,54,337992,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
32534,37,179137,0,0,0,39,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32535,22,325033,1,0,0,35,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32536,34,160216,0,0,0,55,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32537,30,345898,1,0,0,46,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32538,38,139180,0,15020,0,45,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32539,71,287372,1,0,0,10,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32540,45,252208,0,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32541,41,202822,0,0,0,32,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32542,72,129912,1,0,0,25,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32543,45,119199,0,0,0,48,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
32544,31,199655,0,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32545,39,111499,0,0,0,20,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
32546,37,198216,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32547,43,260761,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
32548,65,99359,1,1086,0,60,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32549,43,255835,0,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32550,43,27242,1,0,0,50,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32551,32,34066,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32552,43,84661,1,0,0,45,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32553,32,116138,1,0,0,11,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
32554,53,321865,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32555,22,310152,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32556,27,257302,0,0,0,38,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32557,40,154374,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32558,58,151910,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32559,22,201490,1,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32560,52,287927,0,15024,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [5]:
print(len(list(df_X_train.columns)))
list(df_X_train.columns)

106

['age',
 'fnlwgt',
 'sex',
 'capital_gain',
 'capital_loss',
 'hours_per_week',
 ' Federal-gov',
 ' Local-gov',
 ' Never-worked',
 ' Private',
 ' Self-emp-inc',
 ' Self-emp-not-inc',
 ' State-gov',
 ' Without-pay',
 '?_workclass',
 ' 10th',
 ' 11th',
 ' 12th',
 ' 1st-4th',
 ' 5th-6th',
 ' 7th-8th',
 ' 9th',
 ' Assoc-acdm',
 ' Assoc-voc',
 ' Bachelors',
 ' Doctorate',
 ' HS-grad',
 ' Masters',
 ' Preschool',
 ' Prof-school',
 ' Some-college',
 ' Divorced',
 ' Married-AF-spouse',
 ' Married-civ-spouse',
 ' Married-spouse-absent',
 ' Never-married',
 ' Separated',
 ' Widowed',
 ' Adm-clerical',
 ' Armed-Forces',
 ' Craft-repair',
 ' Exec-managerial',
 ' Farming-fishing',
 ' Handlers-cleaners',
 ' Machine-op-inspct',
 ' Other-service',
 ' Priv-house-serv',
 ' Prof-specialty',
 ' Protective-serv',
 ' Sales',
 ' Tech-support',
 ' Transport-moving',
 '?_occupation',
 ' Husband',
 ' Not-in-family',
 ' Other-relative',
 ' Own-child',
 ' Unmarried',
 ' Wife',
 ' Amer-Indian-Eskimo',
 ' Asian-Pac-Islander',
 ' Black',
 ' Other',
 ' White',
 ' Cambodia',
 ' Canada',
 ' China',
 ' Columbia',
 ' Cuba',
 ' Dominican-Republic',
 ' Ecuador',
 ' El-Salvador',
 ' England',
 ' France',
 ' Germany',
 ' Greece',
 ' Guatemala',
 ' Haiti',
 ' Holand-Netherlands',
 ' Honduras',
 ' Hong',
 ' Hungary',
 ' India',
 ' Iran',
 ' Ireland',
 ' Italy',
 ' Jamaica',
 ' Japan',
 ' Laos',
 ' Mexico',
 ' Nicaragua',
 ' Outlying-US(Guam-USVI-etc)',
 ' Peru',
 ' Philippines',
 ' Poland',
 ' Portugal',
 ' Puerto-Rico',
 ' Scotland',
 ' South',
 ' Taiwan',
 ' Thailand',
 ' Trinadad&Tobago',
 ' United-States',
 ' Vietnam',
 ' Yugoslavia',
 '?_native_country']

In [6]:
path_X_test = path_list[4]
df_X_test = pd.read_csv(path_X_test)
df_X_test

,age,fnlwgt,sex,capital_gain,capital_loss,hours_per_week,Federal-gov,Local-gov,Never-worked,Private,...,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia,?_native_country
0,25,226802,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1,38,89814,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
2,28,336951,1,0,0,40,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3,44,160323,1,7688,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,18,103497,0,0,0,30,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,34,198693,1,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
6,29,227026,1,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7,63,104626,1,3103,0,32,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8,24,369667,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
9,55,104996,1,0,0,10,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
10,65,184454,1,6418,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
11,36,212465,1,0,0,40,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,26,82091,0,0,0,39,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
13,58,299831,1,0,0,35,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,48,279724,1,3103,0,48,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
15,43,346189,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16,20,444554,1,0,0,25,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
17,43,128354,0,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
18,37,60548,0,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
19,40,85019,1,0,0,45,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
20,34,107914,1,0,0,47,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
21,34,238588,0,0,0,35,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
22,72,132015,0,0,0,6,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
23,25,220931,1,0,0,43,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,25,205947,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
25,45,432824,1,7298,0,90,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
26,22,236427,1,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
27,23,134446,1,0,0,54,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
28,54,99516,1,0,0,35,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
29,32,109282,1,0,0,60,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16251,81,26711,1,2936,0,20,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16252,60,117909,1,7688,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16253,39,229647,0,0,1669,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16254,38,149347,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16255,43,23157,1,0,1902,50,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
16256,23,93977,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16257,73,159691,0,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16258,35,176967,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16259,66,344436,0,0,0,8,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16260,27,430340,0,0,0,45,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16261,40,202168,1,15024,0,55,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16262,51,82720,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16263,22,269623,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16264,64,136405,1,0,0,32,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16265,50,139347,0,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
16266,55,224655,0,0,0,32,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16267,38,247547,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16268,58,292710,1,0,0,36,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16269,32,173449,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16270,48,285570,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16271,61,89686,1,0,0,48,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16272,31,440129,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16273,25,350977,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16274,48,349230,1,0,0,40,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
16275,33,245211,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16276,39,215419,0,0,0,36,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16277,64,321403,1,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16278,38,374983,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16279,44,83891,1,5455,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16280,35,182148,1,0,0,60,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [7]:
path_train = path_list[3]
df_train = pd.read_csv(path_train)
df_train

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [8]:
path_test = path_list[1]
df_test = pd.read_csv(path_test)
df_test

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States
6,29,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,Male,0,0,40,United-States
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States
9,55,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418,0,40,United-States
11,36,Federal-gov,212465,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
12,26,Private,82091,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,39,United-States
13,58,?,299831,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,35,United-States
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,48,United-States
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States
16,20,State-gov,444554,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States
17,43,Private,128354,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,30,United-States
18,37,Private,60548,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,White,Female,0,0,20,United-States
19,40,Private,85019,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,45,?
20,34,Private,107914,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,47,United-States
21,34,Private,238588,Some-college,10,Never-married,Other-service,Own-child,Black,Female,0,0,35,United-States
22,72,?,132015,7th-8th,4,Divorced,?,Not-in-family,White,Female,0,0,6,United-States
23,25,Private,220931,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,43,Peru
24,25,Private,205947,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States
25,45,Self-emp-not-inc,432824,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,7298,0,90,United-States
26,22,Private,236427,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States
27,23,Private,134446,HS-grad,9,Separated,Machine-op-inspct,Unmarried,Black,Male,0,0,54,United-States
28,54,Private,99516,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,35,United-States
29,32,Self-emp-not-inc,109282,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,60,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16251,81,?,26711,Assoc-voc,11,Married-civ-spouse,?,Husband,White,Male,2936,0,20,United-States
16252,60,Private,117909,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,7688,0,40,United-States
16253,39,Private,229647,Bachelors,13,Never-married,Tech-support,Not-in-family,White,Female,0,1669,40,United-States
16254,38,Private,149347,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States
16255,43,Local-gov,23157,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,1902,50,United-States
16256,23,Private,93977,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States
16257,73,Self-emp-inc,159691,Some-college,10,Divorced,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States
16258,35,Private,176967,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
16259,66,Private,344436,HS-grad,9,Widowed,Sales,Other-relative,White,Female,0,0,8,United-States
16260,27,Private,430340,Some-college,10,Never-married,Sales,Not-in-family,White,Female,0,0,45,United-States
16261,40,Private,202168,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,55,United-States
16262,51,Private,82720,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
16263,22,Private,269623,Some-college,10,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States
16264,64,Self-emp-not-inc,136405,HS-grad,9,Widowed,Farming-fishing,Not-in-family,White,Male,0,0,32,United-States
16265,50,Local-gov,139347,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,?
16266,55,Private,224655,HS-grad,9,Separated,Priv-house-serv,Not-in-family,White,Female,0,0,32,United-States
16267,38,Private,247547,Assoc-voc,11,Never-married,Adm-clerical,Unmarried,Black,Female,0,0,40,United-States
16268,58,Private,292710,Assoc-acdm,12,Divorced,Prof-specialty,Not-in-family,White,Male,0,0,36,United-States
16269,32,Private,173449,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,United-States
16270,48,Private,285570,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
16271,61,Private,89686,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States
16272,31,Private,440129,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
16273,25,Private,350977,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,40,United-States
16274,48,Local-gov,349230,Masters,14,Divorced,Other-service,Not-in-family,White,Male,0,0,40,United-States
16275,33,Private,245211,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States
16276,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States
16277,64,?,321403,HS-grad,9,Widowed,?,Other-relative,Black,Male,0,0,40,United-States
16278,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States
16279,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States
16280,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States

## Pandas axis
- Axis 0 will act on all the ROWS in each COLUMN
- Axis 1 will act on all the COLUMNS in each ROW

In [9]:
random = np.random.randn(1,2)
diff = pd.DataFrame(random, columns=list('AB'))
display(diff)
diff.mean(axis=1)

          A         B
0  1.626368  1.399649

0    1.513008
dtype: float64

## Normalization

https://morvanzhou.github.io/tutorials/machine-learning/sklearn/3-1-normalization/

In [10]:
def normalize(df_array):
    mean = df_array.mean(axis=0)
    std = df_array.std(axis=0)
    
    # To prevent from divide by inf: if std = 0, replace it with 1
    std[std == 0] = 1
    
    df_array_normalized = (df_array - mean) / std
    return df_array_normalized

In [11]:
# from sklearn import preprocessing
# import numpy as np

# a = np.array([[10, 2.7, 3],
#               [-100, 5, 4],
#               [120, 20, 3]], dtype=np.float64)

# print(preprocessing.scale(a))
# print(normalize(a))

In [12]:
y_train = df_Y_train.values
x_train = df_X_train.values
x_test = df_X_test.values
y_train.shape, x_train.shape, x_test.shape

((32561, 1), (32561, 106), (16281, 106))

In [13]:
y_train = y_train.astype('float')
x_train = x_train.astype('float')
x_test = x_test.astype('float')

y_train = y_train.reshape(-1)

x_train = normalize(x_train)
x_test = normalize(x_test)

print(y_train.shape, x_train.shape, x_test.shape)
print(y_train[0], x_train[0,0], x_test[0,0])

(32561,) (32561, 106) (16281, 106)
0.0 0.030670557354391753 -0.9941292592084697

In [14]:
bias = np.ones(shape= (len(x_train),1))
print(bias.shape)
x_train_bias = np.concatenate([x_train, bias], axis=1)
print(x_train_bias.shape)
print(x_train_bias[0])

(32561, 1)
(32561, 107)
[ 0.03067056 -1.06361075  0.70307135  0.1484529  -0.21665953 -0.03542945
 -0.17429511 -0.26209736 -0.01466381 -1.5167923  -0.18838933 -0.29093568
  4.90769968 -0.02073999 -0.2444502  -0.17175325 -0.19348662 -0.11609195
 -0.07201601 -0.10164955 -0.1422718  -0.12664495 -0.18406376 -0.21053433
  2.25399324 -0.11334387 -0.68994199 -0.23637391 -0.03960742 -0.13419553
 -0.53714425 -0.39750806 -0.02658695 -0.92284068 -0.11403678  1.43105786
 -0.1802846  -0.17735813  2.76348874 -0.01662771 -0.37949517 -0.37774555
 -0.17745022 -0.20957797 -0.25595432 -0.33554133 -0.06780164 -0.38166338
 -0.14260848 -0.35531609 -0.17127887 -0.22710355 -0.24494366 -0.82533335
  1.70899099 -0.17624972 -0.42934582 -0.34403232 -0.22492681 -0.09820087
 -0.18155194 -0.32576824 -0.09161163  0.4130197  -0.02416321 -0.06107342
 -0.0480488  -0.04260602 -0.05409379 -0.04641598 -0.02933708 -0.05714946
 -0.05264698 -0.02985682 -0.06500204 -0.02985682 -0.04437806 -0.03678503
 -0.00554189 -0.01998525 -0.02479131 -0.01998525 -0.05550333 -0.03636406
 -0.02715919 -0.04740236 -0.04993839 -0.04367781 -0.02351838 -0.1419344
 -0.03233087 -0.02073999 -0.03087016 -0.07821827 -0.04296623 -0.03372864
 -0.05927412 -0.01920091 -0.0496284  -0.03960742 -0.02351838 -0.02416321
  0.34095391 -0.04540836 -0.02217266 -0.13502327  1.        ]

# Training

In [15]:
learning_rate = 0.1

In [16]:
w = np.zeros(shape=x_train_bias.shape[1])
w.shape

(107,)

In [17]:
z_train = x_train_bias @ w
z_train.shape, x_train_bias.shape, w.shape

((32561,), (32561, 107), (107,))

In [18]:
def sigmoid(z):
    res = 1 / (1.0 + np.exp(-z))
    return np.clip(res, 1e-8, 1-(1e-8))

y_hat = sigmoid(z_train)
y_hat.shape, z_train.shape

((32561,), (32561,))

In [19]:
y_delta = y_train - y_hat
print(y_delta.shape, y_train.shape, y_hat.shape)
print(y_delta[0], y_train[0], y_hat[0])

(32561,) (32561,) (32561,)
-0.5 0.0 0.5

In [20]:
gradient = x_train_bias.T @ y_delta
gradient.shape, x_train_bias.T.shape, y_delta.shape

((107,), (107, 32561), (32561,))

In [21]:
w = w - learning_rate * gradient
w.shape

(107,)

In [22]:
y_train.shape, np.log(y_hat).shape

((32561,), (32561,))

In [23]:
y_real_0 = y_train
y_real_1 = 1 - y_train
print(y_real_0.shape, y_real_1.shape)
print(y_real_0[0:10], y_real_1[0:10])

(32561,) (32561,)
[0. 0. 0. 0. 0. 0. 0. 1. 1. 1.] [1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]

In [24]:
y_predict_0 = y_hat
y_predict_1 = 1 - y_hat
print(y_predict_0.shape, y_predict_1.shape)
print(y_predict_0[0:10], y_predict_1[0:10])

(32561,) (32561,)
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5] [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]

In [25]:
cross_entropy = - y_real_0 * np.log(y_predict_0) - y_real_1 * np.log(y_predict_1)
print(cross_entropy.shape)
print(cross_entropy[:10])

(32561,)
[0.69314718 0.69314718 0.69314718 0.69314718 0.69314718 0.69314718
 0.69314718 0.69314718 0.69314718 0.69314718]

In [26]:
total_cross_entropy = np.sum(cross_entropy)
total_cross_entropy.shape, total_cross_entropy

((), 22569.565346212377)

In [27]:
mean_cross_entropy = np.mean(cross_entropy)
mean_cross_entropy.shape, mean_cross_entropy

((), 0.6931471805599453)

In [28]:
def shuffle(arr1,arr2):
    id_list = np.arange(len(arr1))
    np.random.shuffle(id_list)
    
    arr1_random = arr1[id_list]
    arr2_random = arr2[id_list]
    return arr1_random,arr2_random
    

# arr = np.array([[0,0],
#                 [1,10],
#                 [2,20]])

# id_list = np.arange(len(arr))
# print(id_list)
# np.random.shuffle(id_list)
# print(id_list)
# arr_random = arr[id_list]
# print(arr_random)

In [29]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
p = np.random.permutation(len(a))
a[p], b[p]

(array([2, 4, 1, 3]), array([20, 40, 10, 30]))

# Simple

In [30]:
epochs = 100
batch_size = 32
learning_rate = 0.0001
# print(x_train_bias.shape[1])
w = np.zeros(shape=x_train_bias.shape[1])

for epoch in range(epochs):
    
    x_train_bias, y_train = shuffle(x_train_bias, y_train)
    
    batch_num = int(len(x_train_bias) / batch_size)
    
    # update parameters
    z_train = x_train_bias @ w
    y_hat = sigmoid(z_train)
    y_delta = y_train - y_hat
    gradient = - x_train_bias.T @ y_delta
    w = w - learning_rate * gradient
    
    # calculate loss 
    y_real_0 = y_train
    y_real_1 = 1 - y_train
    y_predict_0 = y_hat
    y_predict_1 = 1 - y_hat
    cross_entropy = - y_real_0 * np.log(y_predict_0) - y_real_1 * np.log(y_predict_1)
    total_cross_entropy = np.sum(cross_entropy)
    mean_cross_entropy = np.mean(cross_entropy)
    print(total_cross_entropy, mean_cross_entropy)

22569.565346212377 0.6931471805599453
17371.073244085153 0.5334932355912028
13102.248219631836 0.40239084240753775
11865.648539015638 0.36441290313613334
11368.893041331125 0.34915675321185236
11043.605864387213 0.3391666676203806
10869.90451582316 0.3338320234582218
10760.913077708876 0.3304847233717907
10693.039588839514 0.32840022078067366
10645.331146394969 0.32693501877691006
10609.78904812627 0.3258434645166386
10581.307962257983 0.3249687651564136
10557.501803391971 0.3242376402257907
10536.96444983699 0.323606905495439
10518.916279054256 0.3230526175195558
10502.852395207301 0.32255927014549
10488.433549314319 0.3221164444984589
10475.40753849292 0.32171639502757654
10463.580497273124 0.3213531678165021
10452.796181042815 0.32102196434516184
10442.926654938474 0.3207188555308029
10433.864963317088 0.3204405565958382
10425.520883769364 0.3201842966668519
10417.817454565928 0.3199477121269595
10410.688575097742 0.31972877292152396
10404.07704399218 0.3195257223055858
10397.933074247721 0.31933703124129237
10392.213080849066 0.31916136116363336
10386.87871943814 0.31899753445650136
10381.896097005461 0.31884451021177057
10377.23512874845 0.3187013644773948
10372.869004802214 0.31856727387986283
10368.773747641699 0.31844150203131655
10364.927840960296 0.3183233881318232
10361.311917278554 0.3182123373753433
10357.908493102696 0.31810781281602823
10354.701743402124 0.31800932844206636
10351.677308485298 0.3179164432445348
10348.822127875937 0.3178287561154736
10346.124296786675 0.31774590143996423
10343.572941564124 0.3176675452708493
10341.158111189166 0.3175933819965347
10338.870682423993 0.31752313142790434
10336.702276563316 0.31745653624161774
10334.645186163896 0.31739335972985766
10332.692310338014 0.31733338381308973
10330.837097443744 0.3172764072799897
10329.073494183278 0.3172222442241724
10327.395900286558 0.3171707226524541
10325.799128048879 0.31712168324218787
10324.27836613515 0.31707497822963515
10322.829147115706 0.31703047041293897
10321.4473182936 0.31698803225618377
10320.12901543548 0.3169475450826289
10318.870639071763 0.3169088983468494
10317.668833075657 0.31687198897686364
10316.520465268131 0.31683672077848135
10315.42260982883 0.31680300389511473
10314.372531314959 0.31677075431697305
10313.367670126601 0.31673989343467956
10312.40562926184 0.3167103476325003
10311.484162231605 0.31668204791718946
10310.601162018409 0.3166549295788953
10309.754650975156 0.31662893188093594
10308.942771572185 0.3166039977756268
10308.163777910973 0.31658007364365265
10307.416027931655 0.31655710905474815
10306.697976249445 0.31653505654769337
10306.008167561758 0.3165138714278357
10305.345230574156 0.3164935115805459
10304.707872398176 0.31647393729916695
10304.094873379276 0.31645511112617164
10303.505082317028 0.31643699770636735
10302.93741204355 0.3164195636511025
10302.390835329521 0.31640277741253403
10301.864381089908 0.31638660916709893
10301.357130864477 0.31637103070742534
10300.868215550272 0.3163560153419819
10300.396812365327 0.31634153780182817
10299.94214202522 0.3163275741539025
10299.50346611508 0.31631410172031205
10299.080084641872 0.31630109900315934
10298.671333752685 0.3162885456144678
10298.276583606297 0.3162764222108135
10297.895236386235 0.31626471043230353
10297.526724444579 0.3162533928455692
10297.170508566829 0.31624245289047725
10296.826076348862 0.31623187483028353
10296.492940677539 0.31622164370497036
10296.170638307827 0.3162117452875473
10295.858728529283 0.31620216604309703
10295.556791915535 0.3161928930903699
10295.264429151139 0.3161839141657547
10294.981259930113 0.316175217589451
10294.706921921741 0.31616679223370725
10294.441069798451 0.3161586274929655
10294.183374322054 0.31615071325579847
10293.933521484429 0.3161430398785181
10293.691211698684 0.3161355981603355
10293.456159038076 0.3161283793199864

# Train on batch

In [31]:
# about division
2/3, 2//3, int(2/3)

(0.6666666666666666, 0, 0)

In [32]:
len(y_train), batch_size * batch_num

(32561, 32544)

In [55]:
np.round([0.50, 0.51])

array([0., 1.])

In [34]:
a = np.array([1,2,3,4])
b = np.array([1,5,3,6])
c = (a == b)
c, np.sum(c, axis = 0)

(array([ True, False,  True, False]), 2)

the first dimension () = the 2nd group

y_real_0 = group 1

y_real_0 = 0.6 => 1, group 1, salary > 50k

y_real_1 = 0.4 => 0, group 0, salary < 50K

In [56]:
epochs = 100
batch_size = 32
learning_rate = 0.0001

# split (train, val)
split_percent = 0.1
num_sample = len(y_train)
num_sample_train = int(num_sample * (1 - split_percent))
x_train_split = x_train_bias[:num_sample_train]
y_train_split = y_train[:num_sample_train]
x_val_split = x_train_bias[num_sample_train:]
y_val_split = y_train[num_sample_train:]

w = np.zeros(shape=x_train_split.shape[1])
batch_num = len(y_train_split) // batch_size

for epoch in range(epochs):
    
    x_train_split, y_train_split = shuffle(x_train_split, y_train_split)
    
    total_cross_entropy = 0
    total_sample = 0
    
    for i_batch in range(batch_num):
        
        i_batch_start = i_batch * batch_size
        i_batch_end = (i_batch + 1) * batch_size
        
        x_batch = x_train_split[i_batch_start:i_batch_end]
        y_batch = y_train_split[i_batch_start:i_batch_end]
        
        # update parameters
        z_train = x_batch @ w
        y_hat = sigmoid(z_train)
        y_delta = y_batch - y_hat
        gradient = - x_batch.T @ y_delta
        w = w - learning_rate * gradient
        
        # calculate loss
        y_real_0 = y_batch
        y_real_1 = 1 - y_batch
        y_predict_0 = y_hat
        y_predict_1 = 1 - y_hat
        cross_entropy = - y_real_0 * np.log(y_predict_0) - y_real_1 * np.log(y_predict_1)
        
        total_cross_entropy += np.sum(cross_entropy)
        total_sample += len(y_batch)
        
    # calculate accuracy
    z_val = x_val_split @ w
    y_val_predict = sigmoid(z_val)
    y_val_predict_category = np.round(y_val_predict)
    compare = (y_val_predict_category == y_val_split)
    accuracy = np.sum(compare) / len(x_val_split)
    
    # mean cross entropy
    mean_cross_entropy = total_cross_entropy / total_sample
    
    # training log
    log = np.array([total_cross_entropy, mean_cross_entropy, accuracy, total_sample])
    log = ['%.3f'%(x) for x in log]
    print(log)

['15232.008', '0.520', '0.813', '29280.000']
['12003.892', '0.410', '0.832', '29280.000']
['10976.344', '0.375', '0.840', '29280.000']
['10481.857', '0.358', '0.841', '29280.000']
['10196.210', '0.348', '0.843', '29280.000']
['10009.217', '0.342', '0.843', '29280.000']
['9885.684', '0.338', '0.845', '29280.000']
['9790.511', '0.334', '0.846', '29280.000']
['9718.921', '0.332', '0.845', '29280.000']
['9669.751', '0.330', '0.846', '29280.000']
['9623.530', '0.329', '0.846', '29280.000']
['9584.385', '0.327', '0.846', '29280.000']
['9552.899', '0.326', '0.847', '29280.000']
['9526.574', '0.325', '0.846', '29280.000']
['9503.667', '0.325', '0.845', '29280.000']
['9479.788', '0.324', '0.846', '29280.000']
['9462.959', '0.323', '0.846', '29280.000']
['9448.696', '0.323', '0.845', '29280.000']
['9430.119', '0.322', '0.846', '29280.000']
['9418.807', '0.322', '0.846', '29280.000']
['9407.238', '0.321', '0.846', '29280.000']
['9401.078', '0.321', '0.846', '29280.000']
['9387.556', '0.321', '0.846', '29280.000']
['9377.498', '0.320', '0.846', '29280.000']
['9374.270', '0.320', '0.846', '29280.000']
['9365.724', '0.320', '0.847', '29280.000']
['9353.881', '0.319', '0.847', '29280.000']
['9348.930', '0.319', '0.846', '29280.000']
['9345.686', '0.319', '0.846', '29280.000']
['9335.907', '0.319', '0.846', '29280.000']
['9329.312', '0.319', '0.847', '29280.000']
['9325.853', '0.319', '0.846', '29280.000']
['9324.487', '0.318', '0.846', '29280.000']
['9315.064', '0.318', '0.846', '29280.000']
['9315.626', '0.318', '0.846', '29280.000']
['9312.184', '0.318', '0.847', '29280.000']
['9300.308', '0.318', '0.846', '29280.000']
['9299.683', '0.318', '0.847', '29280.000']
['9301.067', '0.318', '0.846', '29280.000']
['9294.387', '0.317', '0.847', '29280.000']
['9294.325', '0.317', '0.847', '29280.000']
['9292.519', '0.317', '0.847', '29280.000']
['9289.420', '0.317', '0.847', '29280.000']
['9282.645', '0.317', '0.847', '29280.000']
['9284.983', '0.317', '0.846', '29280.000']
['9282.401', '0.317', '0.846', '29280.000']
['9277.796', '0.317', '0.847', '29280.000']
['9276.746', '0.317', '0.847', '29280.000']
['9276.675', '0.317', '0.846', '29280.000']
['9272.771', '0.317', '0.847', '29280.000']
['9269.022', '0.317', '0.846', '29280.000']
['9269.644', '0.317', '0.847', '29280.000']
['9263.081', '0.316', '0.847', '29280.000']
['9265.290', '0.316', '0.846', '29280.000']
['9266.300', '0.316', '0.846', '29280.000']
['9265.670', '0.316', '0.847', '29280.000']
['9264.012', '0.316', '0.847', '29280.000']
['9259.001', '0.316', '0.848', '29280.000']
['9256.459', '0.316', '0.846', '29280.000']
['9251.828', '0.316', '0.847', '29280.000']
['9258.394', '0.316', '0.846', '29280.000']
['9254.566', '0.316', '0.846', '29280.000']
['9256.769', '0.316', '0.846', '29280.000']
['9255.169', '0.316', '0.847', '29280.000']
['9254.628', '0.316', '0.847', '29280.000']
['9252.196', '0.316', '0.847', '29280.000']
['9248.314', '0.316', '0.847', '29280.000']
['9249.656', '0.316', '0.847', '29280.000']
['9247.936', '0.316', '0.847', '29280.000']
['9250.651', '0.316', '0.847', '29280.000']
['9247.891', '0.316', '0.847', '29280.000']
['9249.701', '0.316', '0.847', '29280.000']
['9245.427', '0.316', '0.847', '29280.000']
['9240.332', '0.316', '0.847', '29280.000']
['9244.355', '0.316', '0.847', '29280.000']
['9240.866', '0.316', '0.847', '29280.000']
['9244.819', '0.316', '0.847', '29280.000']
['9243.777', '0.316', '0.847', '29280.000']
['9245.160', '0.316', '0.847', '29280.000']
['9240.127', '0.316', '0.848', '29280.000']
['9234.856', '0.315', '0.848', '29280.000']
['9241.160', '0.316', '0.847', '29280.000']
['9242.099', '0.316', '0.847', '29280.000']
['9243.223', '0.316', '0.846', '29280.000']
['9238.615', '0.316', '0.847', '29280.000']
['9242.454', '0.316', '0.848', '29280.000']
['9243.244', '0.316', '0.848', '29280.000']
['9240.525', '0.316', '0.847', '29280.000']
['9235.860', '0.315', '0.848', '29280.000']
['9239.129', '0.316', '0.847', '29280.000']
['9237.205', '0.315', '0.847', '29280.000']
['9238.923', '0.316', '0.846', '29280.000']
['9237.993', '0.316', '0.848', '29280.000']
['9234.316', '0.315', '0.848', '29280.000']
['9237.273', '0.315', '0.847', '29280.000']
['9233.149', '0.315', '0.846', '29280.000']
['9234.738', '0.315', '0.847', '29280.000']
['9237.276', '0.315', '0.848', '29280.000']
['9233.986', '0.315', '0.847', '29280.000']
['9233.723', '0.315', '0.848', '29280.000']