In [1]:
import os
import pandas as pd
import numpy as np
from glob import glob

# Data Preprocessing

In [2]:
path_list = glob(os.path.join(os.getcwd(), 'dataset', '*'))
path_list

['/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/Y_train',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/test.csv',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/X_train',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/train.csv',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/X_test',
 '/Users/chia-yuanchang/My_Project/Machine_Learning_NTU/2_predict_income_by_logistic_regression_and_generative_model/dataset/sample_submission.csv']

In [3]:
path_Y_train = path_list[0]
df_Y_train = pd.read_csv(path_Y_train)
df_Y_train

       label
0          0
1          0
2          0
3          0
4          0
5          0
6          0
7          1
8          1
9          1
10         1
11         1
12         0
13         0
14         1
15         0
16         0
17         0
18         0
19         1
20         1
21         0
22         0
23         0
24         0
25         1
26         0
27         1
28         0
29         0
...      ...
32531      0
32532      1
32533      1
32534      0
32535      0
32536      1
32537      0
32538      1
32539      1
32540      0
32541      0
32542      0
32543      0
32544      0
32545      1
32546      0
32547      0
32548      0
32549      0
32550      0
32551      0
32552      0
32553      0
32554      1
32555      0
32556      0
32557      1
32558      0
32559      0
32560      1

[32561 rows x 1 columns]

In [4]:
path_X_train = path_list[2]
df_X_train = pd.read_csv(path_X_train)
df_X_train

,age,fnlwgt,sex,capital_gain,capital_loss,hours_per_week,Federal-gov,Local-gov,Never-worked,Private,...,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia,?_native_country
0,39,77516,1,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,50,83311,1,0,0,13,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,38,215646,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,53,234721,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,28,338409,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,37,284582,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
6,49,160187,0,0,0,16,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,52,209642,1,0,0,45,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8,31,45781,0,14084,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
9,42,159449,1,5178,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
10,37,280464,1,0,0,80,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
11,30,141297,1,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,23,122272,0,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
13,32,205019,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
14,40,121772,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
15,34,245487,1,0,0,45,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,25,176756,1,0,0,35,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
17,32,186824,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
18,38,28887,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
19,43,292175,0,0,0,45,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,40,193524,1,0,0,60,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
21,54,302146,0,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
22,35,76845,1,0,0,40,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
23,43,117037,1,0,2042,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
24,59,109015,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
25,56,216851,1,0,0,40,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
26,19,168294,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
27,54,180211,1,0,0,60,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
28,39,367260,1,0,0,80,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
29,49,193366,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,33811,0,0,0,99,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32532,34,204461,1,0,0,60,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32533,54,337992,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
32534,37,179137,0,0,0,39,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32535,22,325033,1,0,0,35,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32536,34,160216,0,0,0,55,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32537,30,345898,1,0,0,46,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32538,38,139180,0,15020,0,45,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32539,71,287372,1,0,0,10,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32540,45,252208,0,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32541,41,202822,0,0,0,32,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32542,72,129912,1,0,0,25,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32543,45,119199,0,0,0,48,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
32544,31,199655,0,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32545,39,111499,0,0,0,20,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
32546,37,198216,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32547,43,260761,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
32548,65,99359,1,1086,0,60,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32549,43,255835,0,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32550,43,27242,1,0,0,50,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32551,32,34066,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32552,43,84661,1,0,0,45,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32553,32,116138,1,0,0,11,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
32554,53,321865,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32555,22,310152,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32556,27,257302,0,0,0,38,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32557,40,154374,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32558,58,151910,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32559,22,201490,1,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32560,52,287927,0,15024,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [5]:
print(len(list(df_X_train.columns)))
list(df_X_train.columns)

106

['age',
 'fnlwgt',
 'sex',
 'capital_gain',
 'capital_loss',
 'hours_per_week',
 ' Federal-gov',
 ' Local-gov',
 ' Never-worked',
 ' Private',
 ' Self-emp-inc',
 ' Self-emp-not-inc',
 ' State-gov',
 ' Without-pay',
 '?_workclass',
 ' 10th',
 ' 11th',
 ' 12th',
 ' 1st-4th',
 ' 5th-6th',
 ' 7th-8th',
 ' 9th',
 ' Assoc-acdm',
 ' Assoc-voc',
 ' Bachelors',
 ' Doctorate',
 ' HS-grad',
 ' Masters',
 ' Preschool',
 ' Prof-school',
 ' Some-college',
 ' Divorced',
 ' Married-AF-spouse',
 ' Married-civ-spouse',
 ' Married-spouse-absent',
 ' Never-married',
 ' Separated',
 ' Widowed',
 ' Adm-clerical',
 ' Armed-Forces',
 ' Craft-repair',
 ' Exec-managerial',
 ' Farming-fishing',
 ' Handlers-cleaners',
 ' Machine-op-inspct',
 ' Other-service',
 ' Priv-house-serv',
 ' Prof-specialty',
 ' Protective-serv',
 ' Sales',
 ' Tech-support',
 ' Transport-moving',
 '?_occupation',
 ' Husband',
 ' Not-in-family',
 ' Other-relative',
 ' Own-child',
 ' Unmarried',
 ' Wife',
 ' Amer-Indian-Eskimo',
 ' Asian-Pac-Islander',
 ' Black',
 ' Other',
 ' White',
 ' Cambodia',
 ' Canada',
 ' China',
 ' Columbia',
 ' Cuba',
 ' Dominican-Republic',
 ' Ecuador',
 ' El-Salvador',
 ' England',
 ' France',
 ' Germany',
 ' Greece',
 ' Guatemala',
 ' Haiti',
 ' Holand-Netherlands',
 ' Honduras',
 ' Hong',
 ' Hungary',
 ' India',
 ' Iran',
 ' Ireland',
 ' Italy',
 ' Jamaica',
 ' Japan',
 ' Laos',
 ' Mexico',
 ' Nicaragua',
 ' Outlying-US(Guam-USVI-etc)',
 ' Peru',
 ' Philippines',
 ' Poland',
 ' Portugal',
 ' Puerto-Rico',
 ' Scotland',
 ' South',
 ' Taiwan',
 ' Thailand',
 ' Trinadad&Tobago',
 ' United-States',
 ' Vietnam',
 ' Yugoslavia',
 '?_native_country']

In [6]:
path_X_test = path_list[4]
df_X_test = pd.read_csv(path_X_test)
df_X_test

,age,fnlwgt,sex,capital_gain,capital_loss,hours_per_week,Federal-gov,Local-gov,Never-worked,Private,...,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia,?_native_country
0,25,226802,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1,38,89814,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
2,28,336951,1,0,0,40,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3,44,160323,1,7688,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,18,103497,0,0,0,30,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,34,198693,1,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
6,29,227026,1,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7,63,104626,1,3103,0,32,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8,24,369667,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
9,55,104996,1,0,0,10,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
10,65,184454,1,6418,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
11,36,212465,1,0,0,40,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,26,82091,0,0,0,39,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
13,58,299831,1,0,0,35,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,48,279724,1,3103,0,48,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
15,43,346189,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16,20,444554,1,0,0,25,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
17,43,128354,0,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
18,37,60548,0,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
19,40,85019,1,0,0,45,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
20,34,107914,1,0,0,47,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
21,34,238588,0,0,0,35,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
22,72,132015,0,0,0,6,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
23,25,220931,1,0,0,43,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,25,205947,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
25,45,432824,1,7298,0,90,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
26,22,236427,1,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
27,23,134446,1,0,0,54,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
28,54,99516,1,0,0,35,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
29,32,109282,1,0,0,60,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16251,81,26711,1,2936,0,20,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16252,60,117909,1,7688,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16253,39,229647,0,0,1669,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16254,38,149347,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16255,43,23157,1,0,1902,50,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
16256,23,93977,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16257,73,159691,0,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16258,35,176967,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16259,66,344436,0,0,0,8,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16260,27,430340,0,0,0,45,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16261,40,202168,1,15024,0,55,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16262,51,82720,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16263,22,269623,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16264,64,136405,1,0,0,32,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16265,50,139347,0,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
16266,55,224655,0,0,0,32,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16267,38,247547,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16268,58,292710,1,0,0,36,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16269,32,173449,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16270,48,285570,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16271,61,89686,1,0,0,48,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16272,31,440129,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16273,25,350977,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16274,48,349230,1,0,0,40,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
16275,33,245211,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16276,39,215419,0,0,0,36,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16277,64,321403,1,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16278,38,374983,1,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16279,44,83891,1,5455,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16280,35,182148,1,0,0,60,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [7]:
path_train = path_list[3]
df_train = pd.read_csv(path_train)
df_train

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [8]:
path_test = path_list[1]
df_test = pd.read_csv(path_test)
df_test

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States
6,29,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,Male,0,0,40,United-States
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States
9,55,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418,0,40,United-States
11,36,Federal-gov,212465,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
12,26,Private,82091,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,39,United-States
13,58,?,299831,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,35,United-States
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,48,United-States
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States
16,20,State-gov,444554,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States
17,43,Private,128354,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,30,United-States
18,37,Private,60548,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,White,Female,0,0,20,United-States
19,40,Private,85019,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,45,?
20,34,Private,107914,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,47,United-States
21,34,Private,238588,Some-college,10,Never-married,Other-service,Own-child,Black,Female,0,0,35,United-States
22,72,?,132015,7th-8th,4,Divorced,?,Not-in-family,White,Female,0,0,6,United-States
23,25,Private,220931,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,43,Peru
24,25,Private,205947,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States
25,45,Self-emp-not-inc,432824,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,7298,0,90,United-States
26,22,Private,236427,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States
27,23,Private,134446,HS-grad,9,Separated,Machine-op-inspct,Unmarried,Black,Male,0,0,54,United-States
28,54,Private,99516,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,35,United-States
29,32,Self-emp-not-inc,109282,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,60,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16251,81,?,26711,Assoc-voc,11,Married-civ-spouse,?,Husband,White,Male,2936,0,20,United-States
16252,60,Private,117909,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,7688,0,40,United-States
16253,39,Private,229647,Bachelors,13,Never-married,Tech-support,Not-in-family,White,Female,0,1669,40,United-States
16254,38,Private,149347,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States
16255,43,Local-gov,23157,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,1902,50,United-States
16256,23,Private,93977,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States
16257,73,Self-emp-inc,159691,Some-college,10,Divorced,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States
16258,35,Private,176967,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
16259,66,Private,344436,HS-grad,9,Widowed,Sales,Other-relative,White,Female,0,0,8,United-States
16260,27,Private,430340,Some-college,10,Never-married,Sales,Not-in-family,White,Female,0,0,45,United-States
16261,40,Private,202168,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,55,United-States
16262,51,Private,82720,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
16263,22,Private,269623,Some-college,10,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States
16264,64,Self-emp-not-inc,136405,HS-grad,9,Widowed,Farming-fishing,Not-in-family,White,Male,0,0,32,United-States
16265,50,Local-gov,139347,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,?
16266,55,Private,224655,HS-grad,9,Separated,Priv-house-serv,Not-in-family,White,Female,0,0,32,United-States
16267,38,Private,247547,Assoc-voc,11,Never-married,Adm-clerical,Unmarried,Black,Female,0,0,40,United-States
16268,58,Private,292710,Assoc-acdm,12,Divorced,Prof-specialty,Not-in-family,White,Male,0,0,36,United-States
16269,32,Private,173449,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,United-States
16270,48,Private,285570,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
16271,61,Private,89686,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States
16272,31,Private,440129,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
16273,25,Private,350977,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,40,United-States
16274,48,Local-gov,349230,Masters,14,Divorced,Other-service,Not-in-family,White,Male,0,0,40,United-States
16275,33,Private,245211,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States
16276,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States
16277,64,?,321403,HS-grad,9,Widowed,?,Other-relative,Black,Male,0,0,40,United-States
16278,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States
16279,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States
16280,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States

## Pandas axis
- Axis 0 will act on all the ROWS in each COLUMN
- Axis 1 will act on all the COLUMNS in each ROW

In [9]:
random = np.random.randn(1,2)
diff = pd.DataFrame(random, columns=list('AB'))
display(diff)
diff.mean(axis=1)

          A         B
0 -1.430408  0.584258

0   -0.423075
dtype: float64

## Normalization

https://morvanzhou.github.io/tutorials/machine-learning/sklearn/3-1-normalization/

In [10]:
def normalize(df_array):
    mean = df_array.mean(axis=0)
    std = df_array.std(axis=0)
    
    # To prevent from divide by inf: if std = 0, replace it with 1
    std[std == 0] = 1
    
    df_array_normalized = (df_array - mean) / std
    return df_array_normalized

In [11]:
# from sklearn import preprocessing
# import numpy as np

# a = np.array([[10, 2.7, 3],
#               [-100, 5, 4],
#               [120, 20, 3]], dtype=np.float64)

# print(preprocessing.scale(a))
# print(normalize(a))

In [12]:
y_train = df_Y_train.values
x_train = df_X_train.values
x_test = df_X_test.values
y_train.shape, x_train.shape, x_test.shape

((32561, 1), (32561, 106), (16281, 106))

In [13]:
y_train = y_train.astype('float')
x_train = x_train.astype('float')
x_test = x_test.astype('float')

y_train = y_train.reshape(-1)

x_train = normalize(x_train)
x_test = normalize(x_test)

print(y_train.shape, x_train.shape, x_test.shape)
print(y_train[0], x_train[0,0], x_test[0,0])

(32561,) (32561, 106) (16281, 106)
0.0 0.030670557354391753 -0.9941292592084697

In [21]:
bias = np.ones(shape= (len(x_train),1))
print(bias.shape)
x_train_bias = np.concatenate([x_train, bias], axis=1)
print(x_train_bias.shape)
print(x_train_bias[0])

(32561, 1)
(32561, 107)
[ 0.03067056 -1.06361075  0.70307135  0.1484529  -0.21665953 -0.03542945
 -0.17429511 -0.26209736 -0.01466381 -1.5167923  -0.18838933 -0.29093568
  4.90769968 -0.02073999 -0.2444502  -0.17175325 -0.19348662 -0.11609195
 -0.07201601 -0.10164955 -0.1422718  -0.12664495 -0.18406376 -0.21053433
  2.25399324 -0.11334387 -0.68994199 -0.23637391 -0.03960742 -0.13419553
 -0.53714425 -0.39750806 -0.02658695 -0.92284068 -0.11403678  1.43105786
 -0.1802846  -0.17735813  2.76348874 -0.01662771 -0.37949517 -0.37774555
 -0.17745022 -0.20957797 -0.25595432 -0.33554133 -0.06780164 -0.38166338
 -0.14260848 -0.35531609 -0.17127887 -0.22710355 -0.24494366 -0.82533335
  1.70899099 -0.17624972 -0.42934582 -0.34403232 -0.22492681 -0.09820087
 -0.18155194 -0.32576824 -0.09161163  0.4130197  -0.02416321 -0.06107342
 -0.0480488  -0.04260602 -0.05409379 -0.04641598 -0.02933708 -0.05714946
 -0.05264698 -0.02985682 -0.06500204 -0.02985682 -0.04437806 -0.03678503
 -0.00554189 -0.01998525 -0.02479131 -0.01998525 -0.05550333 -0.03636406
 -0.02715919 -0.04740236 -0.04993839 -0.04367781 -0.02351838 -0.1419344
 -0.03233087 -0.02073999 -0.03087016 -0.07821827 -0.04296623 -0.03372864
 -0.05927412 -0.01920091 -0.0496284  -0.03960742 -0.02351838 -0.02416321
  0.34095391 -0.04540836 -0.02217266 -0.13502327  1.        ]

# Training

In [22]:
learning_rate = 0.1